[workspace]
members = ["crates/*"]
exclude = ["tauri-app/src-tauri"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "CAL-1.0"
homepage = "https://github.com/rainprotocol/rain.orderbook"

[workspace.dependencies]
alloy-ethers-typecast = { git = "https://github.com/rainlanguage/alloy-ethers-typecast", rev = "e7da77fabaa58a651d997bd0bf31e66e94bc2fb5" }
alloy-sol-types = { version = "0.5.4" }
alloy-primitives = "0.5.4"
anyhow = "1.0.70"
clap = { version = "4.2.5", features = ["cargo", "derive"] }
once_cell = "1.17.1"
reqwest = { version = "0.11.17", features = ["json"] }
rust-bigint = "1.2.0"
serde = "1.0.160"
serde_bytes = "0.11.9"
tokio = { version = "1.28.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = "2.5.0"
comfy-table = "7.1.0"
cynic-codegen = { version = "3.4.0", features = ["rkyv"] }
cynic = "3.4.0"
chrono = "0.4.31"
typeshare = "1.0.1"
thiserror = "1.0.56"
strict-yaml-rust = "0.1.2"
dotrain = { git = "https://github.com/rainlanguage/dotrain.git", rev = "46b733a57c390c56fdad54aa9955f99c6d32879c" }
rain-meta = { path = "lib/rain.metadata/crates/cli" }
rain_interpreter_bindings = { path = "lib/rain.interpreter/crates/bindings" }
rain_interpreter_dispair = { path = "lib/rain.interpreter/crates/dispair" }
rain_interpreter_parser = { path = "lib/rain.interpreter/crates/parser" }

[workspace.dependencies.rain_orderbook_bindings]
path = "crates/bindings"

[workspace.dependencies.rain_orderbook_common]
path = "crates/common"

[workspace.dependencies.rain_orderbook_cli]
path = "crates/cli"

[workspace.dependencies.rain_orderbook_subgraph_queries]
path = "crates/subgraph"
