[workspace]
members = ["crates/*"]
exclude = ["tauri-app/src-tauri", "lib/rain.interpreter"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "CAL-1.0"
homepage = "https://github.com/rainprotocol/rain.orderbook"

[workspace.dependencies]
alloy-ethers-typecast = { git = "https://github.com/rainlanguage/alloy-ethers-typecast", rev = "846dae9034c79f3935a0021635c9a6ee2d91f13e" }
alloy-sol-types = { version = "0.5.4" }
alloy-primitives = "0.5.4"
alloy-json-abi = "0.5.4"
alloy-dyn-abi = "0.5.4"
anyhow = "1.0.70"
clap = { version = "4.2.5", features = ["cargo", "derive"] }
once_cell = "1.17.1"
reqwest = { version = "0.11.17", features = ["json"] }
rust-bigint = "1.2.0"
serde = "1.0.160"
futures = "0.3.17"
serde_bytes = "0.11.9"
serde_json = "1.0.112"
serde_yaml = "0.9.32"
tokio = { version = "1.28.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = "2.5.0"
comfy-table = "7.1.0"
cynic-codegen = { version = "3.4.0", features = ["rkyv"] }
cynic = "3.4.0"
chrono = "0.4.31"
typeshare = "1.0.1"
thiserror = "1.0.56"
strict-yaml-rust = "0.1.2"
dotrain = "6.0.1-alpha.10"
dotrain-lsp = "6.0.1-alpha.10"
rain-metadata = { path = "lib/rain.metadata/crates/cli" }
rain_interpreter_bindings = { path = "lib/rain.interpreter/crates/bindings" }
rain_interpreter_dispair = { path = "lib/rain.interpreter/crates/dispair" }
rain_interpreter_parser = { path = "lib/rain.interpreter/crates/parser" }
rain-interpreter-eval = { path = "lib/rain.interpreter/crates/eval" }
csv = "1.3.0"
insta = { version = "1.34.0" }
proptest = "1.4.0"

derive_builder = "0.20.0"

[workspace.dependencies.rain_orderbook_bindings]
path = "crates/bindings"

[workspace.dependencies.rain_orderbook_common]
path = "crates/common"

[workspace.dependencies.rain_orderbook_cli]
path = "crates/cli"

[workspace.dependencies.rain_orderbook_subgraph_client]
path = "crates/subgraph"

[workspace.dependencies.rain_orderbook_app_settings]
path = "crates/settings"

[patch.crates-io]
revm-inspectors = { git = "https://github.com/paradigmxyz/evm-inspectors" }
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "f0e5b194f09c533feb10d1a686ddb9e5946ec107" }
ethers-core = { git = "https://github.com/gakonst/ethers-rs", rev = "f0e5b194f09c533feb10d1a686ddb9e5946ec107" }
ethers-contract = { git = "https://github.com/gakonst/ethers-rs", rev = "f0e5b194f09c533feb10d1a686ddb9e5946ec107" }
ethers-contract-abigen = { git = "https://github.com/gakonst/ethers-rs", rev = "f0e5b194f09c533feb10d1a686ddb9e5946ec107" }
ethers-providers = { git = "https://github.com/gakonst/ethers-rs", rev = "f0e5b194f09c533feb10d1a686ddb9e5946ec107" }
ethers-signers = { git = "https://github.com/gakonst/ethers-rs", rev = "f0e5b194f09c533feb10d1a686ddb9e5946ec107" }
ethers-middleware = { git = "https://github.com/gakonst/ethers-rs", rev = "f0e5b194f09c533feb10d1a686ddb9e5946ec107" }
ethers-solc = { git = "https://github.com/gakonst/ethers-rs", rev = "f0e5b194f09c533feb10d1a686ddb9e5946ec107" }

revm = { git = "https://github.com/bluealloy/revm", branch = "reth_freeze" }
revm-primitives = { git = "https://github.com/bluealloy/revm", branch = "reth_freeze" }
revm-interpreter = { git = "https://github.com/bluealloy/revm", branch = "reth_freeze" }
revm-precompile = { git = "https://github.com/bluealloy/revm", branch = "reth_freeze" }