[package]
name = "rain_orderbook_js_api"
description = "Javascript bindings for common functions accross the app."
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[lib]
crate-type = ["cdylib"]

[target.'cfg(target_family = "wasm")'.dependencies]
cynic = { workspace = true }
reqwest = { workspace = true }
rain_orderbook_subgraph_client = { workspace = true }
js-sys = { version = "0.3.69" }
wasm-bindgen = { version = "0.2.92" }
serde-wasm-bindgen = { version = "0.6.5" }
wasm-bindgen-futures = { version = "0.4.42" }
tsify = { version = "0.4.5", default-features = false, features = ["js", "wasm-bindgen"] }
tokio = { workspace = true, features = ["sync", "macros", "io-util", "rt", "time"] }