[package]
name = "rain_orderbook_subgraph_client"
version = "0.0.1"
edition = "2021"
license = "CAL-1.0"
description = "Subgraph client, queries & schemas for the Rain Orderbook"
homepage = "https://github.com/rainprotocol/rain.orderbook"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cynic = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
typeshare = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
alloy-primitives = { workspace = true }
rain_orderbook_bindings = { workspace = true }
chrono = { workspace = true }
alloy-sol-types = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
# tokio = { workspace = true }
tokio = { version = "1.28.0", features = ["full"] }

[build-dependencies]
cynic-codegen = { workspace = true }

#[cfg_attr(not(target_family = "wasm"), async_trait)]
 #[cfg_attr(target_family = "wasm", async_trait(?Send))]