[package]
name = "rain_orderbook_subgraph_queries"
version = "0.0.1"
edition = "2021"
license = "CAL-1.0"
description = "Subgraph queries & schemas for the Rain Orderbook"
homepage = "https://github.com/rainprotocol/rain.orderbook"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cynic = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
typeshare = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
typeshare-cli = { workspace = true }

[build-dependencies]
cynic-codegen = { workspace = true }
