[package]
name = "rain_orderbook_subgraph_client"
version = "0.0.1"
edition = "2021"
license = "CAL-1.0"
description = "Subgraph client, queries & schemas for the Rain Orderbook"
homepage = "https://github.com/rainprotocol/rain.orderbook"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cynic = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
typeshare = { workspace = true }
serde = { workspace = true }
alloy-primitives = { workspace = true }
rain_orderbook_bindings = { workspace = true }
csv = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[build-dependencies]
cynic-codegen = { workspace = true }
