[package]
name = "rain_orderbook_common"
version = "0.0.1"
edition = "2021"
license = "CAL-1.0"
description = "Rain Orderbook CLI."
homepage = "https://github.com/rainprotocol/rain.orderbook"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rain_orderbook_bindings = { workspace = true }
rain_orderbook_subgraph_queries = { workspace = true }
alloy-primitives = { workspace = true }
alloy-ethers-typecast = { workspace = true }
alloy-sol-types = { workspace = true }
url = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
