[package]
name = "rain_orderbook_common"
version = "0.0.1"
edition = "2021"
license = "CAL-1.0"
description = "Rain Orderbook CLI."
homepage = "https://github.com/rainprotocol/rain.orderbook"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rain_orderbook_bindings = { workspace = true }
alloy-primitives = { workspace = true }
alloy-ethers-typecast = { workspace = true }
anyhow = { workspace = true }
alloy-sol-types = { workspace = true }

[dev-dependencies]
tempfile = "3.9.0"
