[package]
name = "tauri-app"
version = "0.0.0"
description = "Rain Orderbook Tauri App."
edition = "2021"
license = "CAL-1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rain_orderbook_common = { path = "../../crates/common" }
rain_orderbook_subgraph_queries = { path = "../../crates/subgraph" }
alloy-ethers-typecast = { git = "https://github.com/rainlanguage/alloy-ethers-typecast", rev = "ed8d9b2c1747684843a3b63bb31343fb40db10c3" }
alloy-primitives = "0.5.4"
typeshare = "1.0.1"
forker = { git = "https://github.com/rainlanguage/forker", rev = "4108bbb23f167c8a91091453aa442985138f7af3" }
once_cell = "1.19.0"
alloy-dyn-abi = "0.5.4"
alloy-json-abi = "0.5.4"
alloy-sol-types = { version = "0.5.4", features = ["json"] }
reqwest = { version = "0.11.22", features = ["json"] }
chrono = { version = "0.4.32", features = ["serde"] }
uuid = { version = "1.7.0", features = ["serde"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[dev-dependencies]
tauri-cli = "1.5"
tokio = { version = "1.34.0", features = ["full"] }
