name: Deploy subgraph
on:
  workflow_dispatch:
    inputs:
      subgraph-name:
        description: 'Subgraph to deploy (e.g. ob4-mainnet/0.1)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix develop -c rainix-sol-prelude

      - run: nix develop -c graph codegen
        working-directory: subgraph
      - run: nix develop -c graph build
        working-directory: subgraph
      - run: nix develop -c goldsky login --token ${{ secrets.CI_GOLDSKY_TOKEN }}
      - run: nix develop -c goldsky subgraph deploy ${{ inputs.subgraph-name }}
        working-directory: subgraph