name: Deploy webapp to Vercel
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix develop -c rainix-sol-prelude
        working-directory: lib/rain.interpreter
      - run: nix develop -c rainix-rs-prelude
        working-directory: lib/rain.interpreter
      - run: nix develop -c rainix-sol-prelude
        working-directory: lib/rain.interpreter/lib/rain.metadata
      - run: nix develop -c rainix-rs-prelude
        working-directory: lib/rain.interpreter/lib/rain.metadata
      - run: nix develop -c rainix-sol-prelude
      - run: nix develop -c rainix-rs-prelude
      - run: nix develop -c raindex-prelude
      - run: nix develop -c npm run build
        working-directory: packages/orderbook
      - run: nix develop -c npm run build
        working-directory: packages/ui-components
      - run: nix develop -c npm run build
        working-directory: packages/orderbook
      - run: nix develop -c npm run build
        working-directory: packages/webapp

      - uses: amondnet/vercel-action@v25.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Required
          vercel-args: --prebuilt # We want to skip the build step on Vercel, since we've already built our app in the previous step
          working-directory: ./packages/webapp # Optional, use for monorepo
