name: Build docs

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          # https://github.com/foundry-rs/foundry/issues/3440#issuecomment-1641853058
          version: nightly-cc5637a979050c39b3d06bc4cc6134f0591ee8d0
      - name: Generate docs
        run: forge doc -b
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: docs/book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}