name: CI deployments
on: [push]

jobs:
  deploy:
    strategy:
      matrix:
        contract: [
          "src/OrderBook.sol:OrderBook"
        ]
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_KEY: ${{ github.ref == 'refs/heads/main' && secrets.PRIVATE_KEY || secrets.PRIVATE_KEY_DEV }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Report public key to make it easy to send funds for deployments
        run: cast wallet address "${DEPLOYMENT_KEY}"
      - name: Forge deploy contract to mumbai(wip)
        env:
          CI_DEPLOY_RPC_URL: ${{ secrets.CI_DEPLOY_RPC_URL }}
          EXPLORER_VERIFICATION_KEY: ${{ secrets.EXPLORER_VERIFICATION_KEY }}
        run: forge create --rpc-url "${CI_DEPLOY_RPC_URL}" --private-key "${DEPLOYMENT_KEY}" --etherscan-api-key "${EXPLORER_VERIFICATION_KEY}" --verify ${{ matrix.contract }}
