name: Rainix CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref }}-rainix
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  standard-tests:
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        task: [ob-rs-test, rainix-rs-artifacts]
        is-not-main:
          - ${{ github.ref != 'refs/heads/main' }}
        include:
          # Solidity doesn't need to be tested on multiple platforms
          - os: ubuntu-latest
            task: rainix-sol-test
          - os: ubuntu-latest
            task: rainix-sol-static
          - os: ubuntu-latest
            task: rainix-sol-artifacts
          # We don't need to do rust static analysis on multiple platforms
          - os: ubuntu-latest
            task: rainix-rs-static
          # Wasm target doesnt need to run on multiple platforms
          - os: ubuntu-latest
            task: rainix-wasm-artifacts
          - os: ubuntu-latest
            task: rainix-wasm-test
          # Testing JS/TS bindings doesnt need to run on multiple platforms
          - os: ubuntu-latest
            task: test-js-bindings
          # Legal doesnt need to run on multiple platforms
          - os: ubuntu-latest
            task: rainix-sol-legal
        exclude:
          - is-not-main: true
            os: macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      COMMIT_SHA: ${{ github.sha }}
      # This is a test key, we don't broadcast our deploys during automated runs,
      # but we still need a key to run the script. Should go without saying, but
      # NEVER USE THIS IN PRODUCTION FOR ANYTHING.
      DEPLOYMENT_KEY: "0xa590156781b232f3fc5361e153ab2c35ac94d172949d9e983bcbc4a29770c06b"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # https://github.com/actions/runner-images/issues/2840#issuecomment-2272410832
      - run: |
          sudo rm -rf \
            "$AGENT_TOOLSDIRECTORY" \
            /opt/google/chrome \
            /opt/microsoft/msedge \
            /opt/microsoft/powershell \
            /opt/pipx \
            /usr/lib/mono \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/lib/node_modules \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/swift
          df -h

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until the Nix store size is at most this number
          # before trying to save a new cache
          gc-max-store-size-linux: 10G

      - run: ./pointers.sh

      - name: Run ${{ matrix.task }}

        run: nix develop -c ${{ matrix.task }}
