name: 'publish'

# This will trigger the action on each push to the `release` branch.
on:
  push:
    branches:
      - main
      - 2024-01-23-tauri-build

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [
          macos-latest,
          ubuntu-20.04
          # Someone who cares can make windows work.
          # windows-latest
        ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: install rust
        run: nix profile install .#tauri-release-env

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - run: nix run .#rainix-sol-prelude
      - run: nix run .#rainix-rs-prelude

      - name: install frontend dependencies
        run: npm install
        working-directory: ./tauri-app

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__-${{ github.sha }} # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__-${{ github.sha }}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false