name: Tauri Publish

# This will trigger the action on each push to the `release` branch.
on:
  push:
    branches:
      - main

jobs:
  before-publish-tauri:
    steps:
      - run: nix develop .#tauri-shell --command ob-tauri-before-publish
        env: 
          - SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          - SENTRY_ORG=rainlang
          - SENTRY_PROJECT=rain-orderbook
          - COMMIT_SHA=${{ github.sha }}
  publish-tauri:
    needs: before-publish-tauri
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [
            macos-13,
            macos-14,
            ubuntu-22.04,
            # Someone who cares can make windows work.
            # windows-latest
          ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: ./prep-tauri.sh

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          tauriScript: "nix develop -i --keep APPLE_CERTIFICATE --keep APPLE_CERTIFICATE_PASSWORD --keep APPLE_SIGNING_IDENTITY --keep APPLE_ID --keep APPLE_PASSWORD --keep APPLE_TEAM_ID .#tauri-shell --command cargo tauri"
          tagName: app-v__VERSION__-${{ github.sha }} # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "App v__VERSION__-${{ github.sha }}"
          releaseBody: "See the assets to download this version and install."
