name: Tauri builds
on: [push]

jobs:
  build-tauri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix run .#rainix-sol-prelude
      - run: nix develop .#tauri-shell --command cargo build --verbose
      - run: nix run .#ob-tauri-prelude
      - run: nix develop .#tauri-shell --command cargo tauri build --verbose
        working-directory: ./tauri-app
