name: Test metadata

on: [push]

jobs:
  test:
    name: Test metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install rain_cli@0.2.0
      - run: rain meta schema validate -i src/OrderBook.meta.json -s interpreter-caller-v1
