name: Test metadata

on: [push]

jobs:
  test:
    strategy:
      matrix:
<<<<<<< HEAD
        meta-file: [src/concrete/OrderBook.meta.json, src/concrete/GenericPoolOrderBookV3FlashBorrower.meta.json, src/concrete/GenericPoolOrderBookV3ArbOrderTaker.meta.json, src/concrete/RouteProcessorOrderBookV3ArbOrderTaker.meta.json]
=======
        meta-file: [src/concrete/OrderBook.meta.json, src/concrete/GenericPoolOrderBookV3FlashBorrower.meta.json]
>>>>>>> 29553542f23172cb378843a4a0089906daa3d96c
    name: Test metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install rain_cli@0.8.0
      - run: rain meta validate -i ${{ matrix.meta-file }} -m interpreter-caller-meta-v1

