name: Subgraph unit tests
on: [push]

jobs:
  test:
    runs-on: warp-ubuntu-2404-x64-32x-spot

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build subgraph
        run: nix develop -c subgraph-build

      - name: Matchstick tests
        run: nix develop -c subgraph-test
